a, b = input().split()
print(a + '+' + b + '=' + str(int(a) + int(b)))
print(a + '-' + b + '=' + str(int(a) - int(b)))
print(a + '*' + b + '=' + str(int(a) * int(b)))
print(a + '/' + b + '=' + str(int(a) // int(b)))